### ISSUE TITLE
How to trigger authentication from a login page?

### ISSUE THREAD

**Issue by kdekooter** [fromi/spring-google-openidconnect#1]
Great work! I am using your code to migrate existing OpenID login code to OpenID connect. 
What would be the equivalent of posting to `j_spring_openid_security_check`?

**Comment by fromi** [comment]
Hi ! Glad you found this small proof of concept.
Unless I am mistaken, "j_spring_openid_security_check" was the JSP designed to handle OpenId connection when user copy-paste it's OpenId identifier in a login form. I think this has no equivalent in OpenId Connect, I don't think it is designed to allow any connection without the user being redirected to a page from the provider (This famous page "this application would like to:"... - should be unavoidable, for security reasons).

I know that Google provide a Sign-In button (see https://developers.google.com/accounts/docs/OpenIDConnect), which might be the closest match. Link the button to "/login" in my example and you're done.

**Comment by fromi** [comment]
It just reminds me of a great login page example: https://grandcentral.cloudbees.com/login
Look at the "Sign in with Google" button. This link to a cloudbees page, then you are redirected to "accounts.google.com" to validate some authorizations, if it is the first time you log-in.

**Comment by fromi** [comment]
You might also need to consider this if your migration concerns Google OpenId:
https://developers.google.com/accounts/docs/OpenID

**Comment by kdekooter** [comment]
Great pointers, thanks! 
First I have to retrofit your setup into my old skool xml-based spring configuration. To be continued...

**Comment by kdekooter** [comment]
OK. Instead of retrofitting your stuff to XML I decided to migrate the existing Spring Security setup to Java Config. It currently only contains a form login.

I want my setup to look like the CloudBees one you mentioned: users can either login with username/password or with Google.

Do you have any pointers of how to integrate your solution into mine? Here is a snippet of my setup:

```
   protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeRequests()
                .regexMatchers(".*\\.action.*").authenticated()
            .and()
                .formLogin()
                .loginPage("/login.page")
                .failureUrl("/login-failed.page")
                .permitAll()
```

**Comment by fromi** [comment]
No pointers, but I think all you have to do is to decouple both login options in the URLs. Have a URL handle google OAuth2 callback ("/login" in my sample, I suggest you rename this one "/google-oauth2-callback", for example), and the other URLs ("/login.page", "/login-failed.page") handle the classic login way.
In "OpenIDConnectAuthenticationFilter", find the user in your database using the Google identifier, or create a new user if it does not exist yet.

**Comment by kdekooter** [comment]
Hi Romain. Almost there. I can sense it ;-).

In my current setup the app is secured and if a user is not authenticated the login page is shown. The user can either login with username/password or click a "Signin with Google" button, like in the CloudBees example.

How can I trigger the OpenID Connect authentication flow from a button?

**Comment by fromi** [comment]
Hi,
Have a look at spring "OAuth2ClientContextFilter" class. This filter, if placed early in the filter chain, intercept UserRedirectRequiredException thrown by an OAuth2RestTemplate, and transform that into a redirect.
Check my last commit (pushed today): I explicitly add that filter just before the "OpenIDConnectAuthenticationFilter". When I tested with Spring Boot embedded container, this was not necessary because somehow OAuth2ClientContextFilter was in the server filter chain before Spring Security filter chain. But once deployed on Heroku, It was not there anymore, so I had to explicitly declare it (found that bug on another project but I did not update this one before today - now it is more robust).

Then, all you have to do is link your "Signin with Google" button to "/google-oauth2-callback". The OpenIDConnectAuthenticationFilter will try to fetch user profile using OAuth2RestTemplate, it will fail, throw a UserRedirectRequiredException, which will be then be caught by the OAuth2ClientContextFilter, which will redirect the user to Google.

Another (cleaner?) option would be to directly send the user to Google with the button, to avoid the failed request. Problem is to build the right URL. You can see that done in OAuth2ClientContextFilter.redirectUser method, maybe you can find a way to get the redirect URI in the front end.
EDIT: a problem with a direct link is that you would bypass the [anti-forgery state token](https://developers.google.com/accounts/docs/OpenIDConnect#createxsrftoken) created by Spring (@see AuthorizationCodeAccessTokenProvider stateKeyGenerator).

Have fun, and do not hesitate to read Spring code, many answers lie there ;)

**Comment by kdekooter** [comment]
Excellent. Thanks a lot Romain! This is the missing piece of the puzzle.

I hooked up the button to the callback URL and added the filter to my configuration like so:

```
http.addFilterAfter(oAuth2ClientContextFilter(), 
             AbstractPreAuthenticatedProcessingFilter.class)
        .addFilterAfter(openIdConnectAuthenticationFilter(), 
             OAuth2ClientContextFilter.class)
        .exceptionHandling().authenticationEntryPoint(openIdauthenticationEntryPoint());
```

**Comment by kdekooter** [comment]
I am sorry Romain, but Spring Security still does not really fit in my brain :-(. In my old setup I configured an AuthenticationUserDetailsService. Where would that fit in this picture?

**Comment by fromi** [comment]
Have a look at @AuthenticationPrincipal annotation. Here is my Rest controller to get user info on client side:

```
@RestController
public class AuthenticationController {

    @RequestMapping(method = GET, value = "/user")
    public User getUser(@AuthenticationPrincipal User user) {
        return user;
    }
}
```

**Comment by kdekooter** [comment]
With a lot of close reading of the sources for OpenID I managed to make things work. Thanks again!
